apiVersion: v2
type: application
name: jellyfin
description: Jellyfin is the volunteer-built media solution that puts you in control of your media.
version: 1.0.1
appVersion: 10.8.9
kubeVersion: '>=1.20'
home: https://jellyfin.org/
icon: https://raw.githubusercontent.com/komodorio/helm-dashboard/main/pkg/dashboard/static/logo.svg
keywords:
  - jellyfin
  - media-server
  - plex
sources:
  - https://github.com/jellyfin/jellyfin
  - https://github.com/belug-apps/catalog/tree/main/charts/jellyfin
maintainers:
  - name: xunleii
    url: https://github.com/belug-apps
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.2.2
