---
# Source: actual/templates/neworkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: actual
  annotations:
    annotations: enabled
  labels:
    app.kubernetes.io/name: actual
    helm.sh/chart: actual-1.0.0
    app.kubernetes.io/instance: actual
    app.kubernetes.io/managed-by: Helm
    commonLabels01: enabled
    commonLabels02: enabled
spec:
  ingress:
    - ports:
        - port: 8096
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
  egress: 
    - ports:
      - port: 8080
        protocol: TCP
      to:
      - ipBlock:
          cidr: 0.0.0.0/0
  podSelector:
    matchLabels:
      app.kubernetes.io/name: actual
      app.kubernetes.io/instance: actual
      podLabels: enabled
  policyTypes:
  - Ingress
  - Egress
