{{- range $type, $issuers := .Values.clusterIssuers }}
{{- range $name, $issuer := $issuers }}
{{ $_ := set $issuer "type" ($type | lower) }}
{{ $_ = set $issuer "name" $name }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $type | lower }}-{{ $issuer.name }}
  {{- if $issuer.annotations }}
  annotations:
    {{- with $issuer.annotations }}
    {{- toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
  labels: {{ include "issuer.labels" $ | nindent 4 }}
    {{- with $issuer.labels }}
    {{- toYaml . | indent 4 }}
    {{- end }}
spec:
  {{ $type }}: {{ if $issuer.spec }}{{ include "issuer.spec.render" (merge dict $ $issuer) | nindent 4 }}{{ else }}{}{{ end }}
{{- if .credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "issuer.crendentials.name" $issuer }}
  namespace: {{ include "issuer.crendentials.namespace" (merge dict $ $issuer) }}
  labels: {{ include "issuer.labels" $ | nindent 4 }}
    issuer.cert-manager.io/name: {{ $issuer.name }}
type: Opaque
stringData: {{ $issuer.credentials | toYaml | nindent 2 }}
{{- end }}{{/* if .credentials */}}
{{- end }}{{/* range $name, $issuer := $issuers */}}
{{- end }}{{/* range $type, $issuers := .Values.issuers */}}
