{{- if .Values.persistence.data.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" $ }}-data
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
spec: {{ toYaml .Values.persistence.data.volumeClaimSpec | nindent 2 }}
{{- end }}
