apiVersion: v2
name: cert-manager
version: 1.10.2
appVersion: v1.10.1
kubeVersion: ">= 1.20.0-0"
description: A Helm chart for cert-manager
home: https://github.com/cert-manager/cert-manager
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/d53c0b9270f8cd90d908460d69502694e1838f5f/logo/logo-small.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/cert-manager/cert-manager
  - https://github.com/belug-apps/catalog/tree/main/charts/cert-manager
maintainers:
  - name: belug-apps
    url: https://github.com/belug-apps
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.10.1
    condition: cert-manager.enabled
