---
name: Synchronize labels
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  repository_dispatch:
    types: [sync-labels]
  schedule:
    - cron: 0 3 * * 0,3
  workflow_dispatch:

jobs:
  sync-labels:
    name: Synchronize org. '${{ github.repository_owner }}' labels
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: belug-apps/.github
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  trigger-sync-everywhere:
    name: Trigger all org. '${{ github.repository_owner }}' repositories to sync their labels
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dispatch 'sync-label' events on all org. repositories
        run: |
          curl --silent \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/orgs/${{ github.repository_owner }}/repos?per_page=100 \
          | jq '.[].name' --raw-output \
          | xargs --replace={} curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository_owner }}/{}/dispatches \
              -d '{"event_type": "sync-labels"}'
