---
name: Lint (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/lint.helm.yml
      - charts/**

env:
  HELM_CONFIG_HOME: ${{ github.workspace }}/e2e/~helm

jobs:
  # Lint all charts using the official chart-testing CLI.
  chart_testing:
    name: Chart testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # tag=v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.pull_request.base.ref }}

  updated_charts:
    name: List updated charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 3
      - uses: tj-actions/changed-files@7f2aa19bdcf4a00195671e368091a1e32a694ac5 # v35.5.2
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/**
          json: true
      - id: set-matrix
        run: echo "matrix={\"chart\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  validations:
    name: Check if all files are up-to-date (${{ matrix.chart }})
    needs: [updated_charts]
    runs-on: ubuntu-latest
    if: needs.updated_charts.outputs.matrix != '{"chart":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.updated_charts.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v3.3.0

      - name: Build helm dependencies
        run: helm dependencies build
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}

      - name: Build out the charts/ directory with all depending files
        run: just build-external
        working-directory: ${{ github.workspace }}/${{ matrix.chart }}

      - uses: tj-actions/verify-changed-files@9ed3155b72ba709881c967f75611fc5852f773b9 # v13
        id: get-diff-values
        continue-on-error: true
        with:
          files: |
            ${{ matrix.chart }}/values.yaml
      - name: Assert that values.yaml is up-to-date
        if: steps.get-diff-values.outputs.files_changed == 'true'
        run: |
          # shellcheck disable=SC2016
          echo '::error file=${{ matrix.chart }}/values.yaml,line=1,title=values.yml not up-to-date::${{ matrix.chart }}/values.yaml must be updated. Please run `just build-external` to update it.'

      - uses: tj-actions/verify-changed-files@9ed3155b72ba709881c967f75611fc5852f773b9 # v13
        id: get-diff-readme
        continue-on-error: true
        with:
          files: |
            ${{ matrix.chart }}/README.md
      - name: Assert that README.md is up-to-date
        if: steps.get-diff-readme.outputs.files_changed == 'true'
        run: |
          # shellcheck disable=SC2016
          echo '::error file=${{ matrix.chart }}/README.md,line=1,title=README.md not up-to-date::${{ matrix.chart }}/README.md must be updated. Please run `just build-external` to update it.'

      - uses: tj-actions/verify-changed-files@9ed3155b72ba709881c967f75611fc5852f773b9 # v13
        id: get-diff-validation
        continue-on-error: true
        with:
          files: |
            ${{ matrix.chart }}/validation/*
      - name: Assert that validation/ is up-to-date
        if: steps.get-diff-validation.outputs.files_changed == 'true'
        run: |
          # shellcheck disable=SC2016
          echo '::error title=validation/ not up-to-date::${{ matrix.chart }}/validation must be updated. Please run `just build-external` to update it.'

      - name: Exit if a file is not up-to-date
        if: steps.get-diff-values.outputs.files_changed == 'true' || steps.get-diff-readme.outputs.files_changed == 'true' || steps.get-diff-validation.outputs.files_changed == 'true'
        run: exit 1
