---
name: Security (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - charts/**
  push:
    branches: [main]
    paths:
      - charts/**

concurrency:
  group: ${{ github.ref }}/helm-security
  cancel-in-progress: true

jobs:
  updated_charts:
    name: List updated charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 3
      - uses: tj-actions/changed-files@7f2aa19bdcf4a00195671e368091a1e32a694ac5 # v35.5.2
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/*/templates/**
            charts/*/Chart.lock
            charts/*/Chart.yaml
            charts/*/README.md
            charts/*/values.yaml
          json: true
      - id: set-matrix
        run: echo "matrix={\"chart\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  trivy:
    name: Trivy scan (${{ matrix.chart }})
    needs: [updated_charts]
    runs-on: ubuntu-latest
    if: needs.updated_charts.outputs.matrix != '{"chart":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.updated_charts.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      # NOTE: this is used to debug trivy reports
      - uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # 0.9.1
        with:
          hide-progress: false
          scan-ref: ${{ matrix.chart }}
          scan-type: config
          skip-dirs: charts # we can't do anything to fix dependencies, so we skip them
          trivyignores: ${{ matrix.chart }}/.trivyignore

      - uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # 0.9.1
        with:
          exit-code: '1'
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ matrix.chart }}
          scan-type: config
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL # NOTE: avoid reporting LOW issues
          skip-dirs: charts # we can't do anything to fix dependencies, so we skip them
          trivyignores: ${{ matrix.chart }}/.trivyignore
      - uses: github/codeql-action/upload-sarif@89c5165e5a26e2e039e88c2d1abfa088c0261d4f # tag=codeql-bundle-20221211
        if: always()
        with:
          category: trivy-helm-syntax
          sarif_file: trivy-results.sarif
